fix: Export and hide `errorMessage` and `errorCode`
temporalio/sdk-typescript pull request #896
Opened 2022-09-29 03:32 UTC by lorensr

These used to be re-exported from `@temporalio/common`, but were moved in: https://github.com/temporalio/sdk-typescript/pull/881/files#diff-b3f127f417ba115081f7791c1ab78f6a143a3287346c90fdfacc22ddf281ebed

2022-09-29 03:34 UTC, bergundy requested changes
These are internal utilities that should not be exported

2022-09-29 03:51 UTC, lorensr commented
Alternatively, we could update the CHANGELOG to say it's a breaking bugfix?

2022-09-29 05:11 UTC, bergundy commented
I guess we can wrap them and export them as deprecated and hidden like we did with some of the other internals

2022-09-30 00:32 UTC, bergundy commented
@lorensr I think we can close this.
If you feel it's important enough, let's wrap these functions with deprecated, internal wrappers.

2022-10-02 02:34 UTC, lorensr commented
Closing in favor of #897

2022-10-02 02:34 UTC, closed without merging